---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- releaseName: omg-shoes
  namespace: default
  name: omg-shoes
  version: 4.2.2
  repo: https://kenmoini.github.io/multiverse-of-multicluster-madness/chart-repo/
  valuesInline:
    replicaCount: 2