---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhacm-policies
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/kenmoini/argocd-policygen-helm-combo-wombo'
    targetRevision: HEAD
    ## Path is the repo directory that containers the cluster(s) configuration and deployment manifests
    path: policy-generators/atomic-pg/infinite-mario
    ## Enable recursive sub-directory search to enable management of multiple cluster from this single Application
    directory:
      recurse: false
  project: default
  syncPolicy:
    automated:
      #prune: true
      allowEmpty: true
      # selfHeal: false # overrides changes made on the cluster that drift from git state
    syncOptions:
      - CreateNamespace=true