---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops # this will create the Policy/PlacementBinding in the openshift-gitops namespace

generators:
  - policygenerator.yaml

commonLabels:
  manifest-group: infinite-mario

commonAnnotations:
  argocd.argoproj.io/compare-options: IgnoreExtraneous