---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infinite-mario

generators:
  - policygenerator.yaml

commonLabels:
  manifest-group: infinite-mario

commonAnnotations:
  argocd.argoproj.io/compare-options: IgnoreExtraneous